import type { Metadata } from "next"
import "./globals.css"
import { Inter } from "next/font/google"
import { Header } from "@/components/Header"
import { GeneralContextProvider } from "@/contexts/generalContext/GeneralContext"
import { Footer } from "@/components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-4 2xl:mx-[15%] xl:pt-2`}>
        <GeneralContextProvider>
          <Header />
          {children}
          <Footer />
        </GeneralContextProvider>
      </body>
    </html>
  )
}
